version: '3.9'

services:
  mysql_db:
    image: mysql:5.7
    environment:   # Set up mysql database name and password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: graficos_teste
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - app-tier
  
  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql_db
    networks:
      - app-tier
    command:
      tail -f /dev/null
    ports:
      - "5000:5000"

networks:
  app-tier:
    driver: bridge


